version: "3.9"

services:
  sdb:
    container_name: sdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: Thanh@123456
      ACCEPT_EULA: Y
    ports:
      - "1444:1433"
    networks:
      - mynetwork

  ssjd-api:
    container_name: ssjd-api
    build:
      context: ./
      dockerfile: StoreSellingJapaneseDomestics\Dockerfile
    ports:
      - 5255:8080
    networks:
      - mynetwork
    environment:
      ASPNETCORE_ENVIRONMENT : Staging
    volumes:
      - '../StoreSellingJapaneseDomestics/StoreSellingJapaneseDomestics:/app/data'
    depends_on:
      - sdb
      
networks:
  mynetwork:
    driver : bridge

                      

