version: '3.8'


services:
  sdb:
    container_name: sdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Thanh@123456
      ACCEPT_EULA: Y
    ports:
      - "1444:1433"
    networks:
      - demo-mynetwork

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongodb_container
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   networks:
  #     - demo-mynetwork

  # mongo-express:
  #   image: mongo-express:1.0
  #   container_name: mongo_express_container
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - demo-mynetwork
  # postgres:
  #   container_name: postgres_container
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root       
  #   ports:
  #     - "5432:5432"                  

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  
networks:
  demo-mynetwork:
    driver : bridge

                      

